### ISSUE TITLE
Weird inverse color for some faces

### ISSUE THREAD

**Issue by milouse** [dracula/emacs#100]
_Originally posted by @dungnq271 in https://github.com/dracula/emacs/issues/59#issuecomment-1718738200_

Hi I accidentally `(set-face-background 'default "#2" nil )` and the background worked. 
But in a tmux session I don't know why some of the words are highlighted in blue. The colours work ok outside tmux.
![image](https://github.com/dracula/emacs/assets/51025577/ba5ff513-87ae-4249-bd12-a04fe244fafc)

**Comment by milouse** [comment]
@dungnq271 Please continue the discussion here.

I’m not sure your new background is for something here. It looks like two faces are "inverted": `font-lock-builtin-face` and `font-lock-type-face`. But the later actually inherit the configuration of the former. Thus I think you just have an issue with `font-lock-builtin-face`. Can you just check that you didn’t accidentally also put it as `inverse-video`?

If you do a `M-x describe-face RET font-lock-builtin-face` you should have the following result:

```
Face: font-lock-builtin-face (sample) (customize this face)

Documentation:
Font Lock mode face used to highlight builtins.

Defined in ‘font-lock.el’.


           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: italic
       Foreground: #8be9fd
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: unspecified
```

If the `Inverse` line shows anything else than "unspecified", you must found what might have changed it.
